# Generated by Django 4.0.5 on 2022-07-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_detail',
        ),
    ]
