# Generated by Django 4.1.5 on 2023-01-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_lecturer_detail_dateofreg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer_detail',
            name='units_teaching',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
