# Generated by Django 4.1.5 on 2023-01-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_lecturer_detail_units_teaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer_detail',
            name='department',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
