# Generated by Django 4.1.5 on 2023-01-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_lecturer_detail_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer_detail',
            name='dateofreg',
            field=models.DateField(default='e.g 2016-09-23'),
        ),
    ]
