# Generated by Django 4.1.5 on 2023-01-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
                ('lecturer_id', models.IntegerField()),
                ('dateofattendance', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_names', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images')),
                ('course', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
                ('dateofattendance', models.DateField(auto_now=True)),
            ],
        ),
    ]
