# Generated by Django 4.1.5 on 2023-01-31 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_lecturer_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer_report',
            name='lecturer_id',
            field=models.IntegerField(null=True),
        ),
    ]
