# Generated by Django 4.1.5 on 2023-02-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_lecturer_report_lecturer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer_report',
            name='date',
            field=models.DateField(default='2016-09-23 00:00:00'),
        ),
    ]
