# Generated by Django 4.1.5 on 2023-02-20 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_lecturer_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer_report',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
