# Generated by Django 4.1.5 on 2023-02-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_alter_lecturer_report_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_names', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('dateofattendance', models.CharField(max_length=100)),
            ],
        ),
    ]
