# Generated by Django 4.1.5 on 2023-02-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_student_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_report',
            name='faculty',
        ),
    ]
