# Generated by Django 4.0.5 on 2022-07-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_names', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='pics')),
                ('course', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
            ],
        ),
    ]
