# Generated by Django 4.0.5 on 2022-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stud_attendance',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
