# Generated by Django 4.1.5 on 2023-01-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_stud_attendance_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_names', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=100)),
                ('picture', models.ImageField(upload_to='images')),
                ('course', models.CharField(max_length=100)),
                ('cohort', models.CharField(max_length=100)),
                ('dateofreg', models.DateField(auto_now=True)),
                ('units', models.CharField(max_length=99)),
            ],
        ),
        migrations.DeleteModel(
            name='Stud_attendance',
        ),
    ]
