# Generated by Django 4.1.5 on 2023-01-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_student_details_delete_stud_attendance'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_details',
            new_name='Student_detail',
        ),
    ]
