# Generated by Django 4.1.5 on 2023-01-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_rename_student_details_student_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='faculty',
            field=models.CharField(default='e.g CIT', max_length=100),
        ),
    ]
