# Generated by Django 4.1.5 on 2023-01-29 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_student_detail_dateofreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_detail',
            name='category',
            field=models.CharField(default='Student', max_length=100),
        ),
    ]
