# Generated by Django 4.1.5 on 2023-01-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_student_detail_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_detail',
            old_name='stud_names',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='student_detail',
            name='lname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
